[DEFAULT]
checks = -WhitespaceCheck,-VisibilityCheck,-MissingRemoteIdCheck
arches = amd64
cache = no
reporter = StrReporter

[gentoo]
class = pkgcore.ebuild.repo_objs.RepoConfig
location = /tmp/gentoo
repo_id = gentoo
masters =
sync-type = git
sync-uri = https://github.com/gentoo-mirror/gentoo.git

[guru]
class = pkgcore.ebuild.repo_objs.RepoConfig
location = /tmp/guru
repo_id = guru
masters = gentoo
sync-type = git
sync-uri = https://github.com/gentoo-mirror/guru.git
