name: Check QA with pkgcheck
on:
  push:

jobs:
  build:
    runs-on: alpine-tools
    container:
      volumes:
        - /mirrors:/mirrors
    steps:
      - uses: actions/checkout@v7
      - id: QA
        shell: sh
        name: QA
        run: |
          set -eux

          GENTOO_LOCATION="/mirrors/gentoo"
          GURU_LOCATION="/mirrors/gentoo-overlays/guru"
          OVERLAY_LOCATION="$(pwd)"

          PROFILE=default/linux/amd64/23.0

          export PATH="$HOME/.local/bin:$PATH"

          mkdir -p /etc/portage

          cat >/etc/portage/repos.conf <<EOF
          [DEFAULT]
          main-repo = gentoo

          [gentoo]
          location = ${GENTOO_LOCATION}

          [guru]
          location = ${GURU_LOCATION}
          masters = gentoo

          [melody]
          location = ${OVERLAY_LOCATION}
          masters = gentoo guru
          EOF

          ln -s "${GENTOO_LOCATION}/profiles/${PROFILE}" "/etc/portage/make.profile"

          uvx -w requests pkgcheck scan --exit error,warning,style . && echo "check successful!"

