# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.17.0
# renovate: datasource=github-tags depName=cross-rs/cross
# Current version: 0.2.5

EAPI=8

CRATES="
	addr2line@0.17.0
	adler@1.0.2
	aho-corasick@0.7.18
	atty@0.2.14
	autocfg@1.1.0
	backtrace@0.3.66
	bitflags@1.3.2
	cc@1.0.73
	cfg-if@1.0.0
	clap@3.2.8
	clap_derive@3.2.7
	clap_lex@0.2.4
	color-eyre@0.6.1
	color-spantrace@0.2.0
	const-sha1@0.2.0
	ctrlc@3.2.2
	directories@4.0.1
	dirs-sys@0.3.7
	dunce@1.0.2
	either@1.7.0
	eyre@0.6.8
	fastrand@1.7.0
	getrandom@0.2.7
	gimli@0.26.1
	hashbrown@0.12.2
	heck@0.4.0
	hermit-abi@0.1.19
	home@0.5.3
	indenter@0.3.3
	indexmap@1.9.1
	instant@0.1.12
	is_ci@1.1.1
	itoa@1.0.2
	lazy_static@1.4.0
	libc@0.2.126
	linked-hash-map@0.5.6
	memchr@2.5.0
	miniz_oxide@0.5.3
	nix@0.24.1
	object@0.29.0
	once_cell@1.13.0
	os_str_bytes@6.1.0
	owo-colors@3.4.0
	pin-project-lite@0.2.9
	proc-macro-error-attr@1.0.4
	proc-macro-error@1.0.4
	proc-macro2@1.0.40
	quote@1.0.20
	redox_syscall@0.2.13
	redox_users@0.4.3
	regex-syntax@0.6.27
	regex@1.6.0
	remove_dir_all@0.5.3
	rustc-demangle@0.1.21
	rustc_version@0.4.0
	ryu@1.0.10
	same-file@1.0.6
	semver@1.0.12
	serde@1.0.138
	serde_derive@1.0.138
	serde_ignored@0.1.3
	serde_json@1.0.82
	serde_yaml@0.8.25
	sharded-slab@0.1.4
	shell-escape@0.1.5
	shell-words@1.1.0
	strsim@0.10.0
	supports-color@1.3.0
	syn@1.0.98
	tempfile@3.3.0
	termcolor@1.1.3
	textwrap@0.15.0
	thiserror-impl@1.0.31
	thiserror@1.0.31
	thread_local@1.1.4
	toml@0.5.9
	tracing-core@0.1.28
	tracing-error@0.2.0
	tracing-subscriber@0.3.14
	tracing@0.1.35
	unicode-ident@1.0.1
	valuable@0.1.0
	version_check@0.9.4
	walkdir@2.3.2
	wasi@0.11.0+wasi-snapshot-preview1
	which@4.2.5
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-util@0.1.5
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	yaml-rust@0.4.5
"

inherit cargo

DESCRIPTION="“Zero setup” cross compilation and “cross testing” of Rust crates"
HOMEPAGE="https://github.com/cross-rs/cross"
SRC_URI="
	https://github.com/cross-rs/cross/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"

S="${WORKDIR}/cross-0.2.5"
LICENSE="|| ( Apache-2.0 MIT )"
# Dependent crate licenses
LICENSE+=" Apache-2.0 BSD CC0-1.0 ISC MIT"
SLOT="0"
KEYWORDS="~amd64"

