# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.16.0
# renovate: datasource=github-tags depName=xeome/zmem
# Current version: 0.2.4

EAPI=8

CRATES="
	anstream@1.0.0
	anstyle-parse@1.0.0
	anstyle-query@1.1.5
	anstyle-wincon@3.0.11
	anstyle@1.0.14
	clap@4.6.6
	clap_builder@4.6.6
	clap_derive@4.6.4
	clap_lex@1.1.0
	colorchoice@1.0.5
	colored@3.1.1
	heck@0.5.0
	is_terminal_polyfill@1.70.2
	once_cell_polyfill@1.70.2
	proc-macro2@1.0.107
	quote@1.0.47
	strsim@0.11.1
	syn@3.0.4
	unicode-ident@1.0.24
	utf8parse@0.2.2
	windows-link@0.2.1
	windows-sys@0.61.2
"

inherit cargo

DESCRIPTION="Zmem is a Linux memory monitoring program that displays detailed information ..."
HOMEPAGE="https://github.com/xeome/zmem"
SRC_URI="
	https://github.com/xeome/zmem/archive/v${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"

S="${WORKDIR}/Zmem-0.2.4"
LICENSE="GPL-3"
# Dependent crate licenses
LICENSE+=" MIT MPL-2.0 Unicode-3.0"
SLOT="0"
KEYWORDS="~amd64"
