# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.16.0
# renovate: datasource=gitlab-tags depName=Zer1t0/dhcplayer
# Current version: 0.1.8

EAPI=8

CRATES="
	aho-corasick@0.7.18
	ansi_term@0.11.0
	atty@0.2.11
	autocfg@1.0.1
	bitflags@1.2.1
	cc@1.0.68
	cfg-if@1.0.0
	chrono@0.4.19
	clap@2.33.3
	ctrlc@3.1.9
	getrandom@0.2.2
	glob@0.3.1
	ipnetwork@0.20.0
	lazy_static@0.2.11
	libc@0.2.140
	log@0.4.14
	memchr@2.4.0
	minimal-lexical@0.2.1
	nix@0.20.0
	no-std-net@0.6.0
	nom@7.1.3
	num-integer@0.1.44
	num-traits@0.2.14
	numtoa@0.1.0
	pnet@0.33.0
	pnet_base@0.33.0
	pnet_datalink@0.33.0
	pnet_macros@0.33.0
	pnet_macros_support@0.33.0
	pnet_packet@0.33.0
	pnet_sys@0.33.0
	pnet_transport@0.33.0
	ppv-lite86@0.2.10
	proc-macro2@1.0.52
	quote@1.0.26
	rand@0.8.3
	rand_chacha@0.3.0
	rand_core@0.6.2
	rand_hc@0.3.0
	redox_syscall@0.2.8
	redox_termios@0.1.2
	regex-syntax@0.6.28
	regex@1.7.1
	serde@1.0.126
	socket2@0.4.4
	stderrlog@0.4.3
	strsim@0.8.0
	syn@1.0.109
	termcolor@1.1.2
	termion@1.5.6
	textwrap@0.11.0
	thread_local@0.3.4
	time@0.1.43
	unicode-ident@1.0.8
	unicode-width@0.1.8
	unreachable@1.0.0
	vec_map@0.8.2
	void@1.0.2
	wasi@0.10.2+wasi-snapshot-preview1
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-util@0.1.5
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
"

inherit cargo

DESCRIPTION="A tool to play and attack DHCP"
HOMEPAGE="https://gitlab.com/Zer1t0/dhcplayer"
SRC_URI="
	https://gitlab.com/Zer1t0/dhcplayer/-/archive/v${PV}/dhcplayer-v${PV}.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="AGPL-3"
# Dependent crate licenses
LICENSE+=" MIT Unicode-DFS-2016"
SLOT="0"
KEYWORDS="~amd64"
