# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.16.0
# renovate: datasource=github-tags depName=JakWai01/lurk
# Current version: 0.3.14

EAPI=8

CRATES="
	aho-corasick@1.1.4
	anstream@0.6.21
	anstyle-parse@0.2.7
	anstyle-query@1.1.5
	anstyle-wincon@3.0.11
	anstyle@1.0.13
	anyhow@1.0.100
	bitflags@2.10.0
	byteorder@1.5.0
	cfg-if@1.0.4
	cfg_aliases@0.2.1
	clap@4.5.53
	clap_builder@4.5.53
	clap_derive@4.5.49
	clap_lex@0.7.6
	colorchoice@1.0.4
	comfy-table@7.2.1
	console@0.16.1
	crossterm@0.29.0
	crossterm_winapi@0.9.1
	document-features@0.2.12
	encode_unicode@1.0.0
	errno@0.3.14
	heck@0.5.0
	is_terminal_polyfill@1.70.2
	itoa@1.0.15
	libc@0.2.178
	linux-raw-sys@0.11.0
	litrs@1.0.0
	lock_api@0.4.14
	log@0.4.29
	memchr@2.7.6
	nix@0.30.1
	once_cell@1.21.3
	once_cell_polyfill@1.70.2
	parking_lot@0.12.5
	parking_lot_core@0.9.12
	proc-macro2@1.0.103
	quote@1.0.42
	redox_syscall@0.5.18
	regex-automata@0.4.13
	regex-syntax@0.8.8
	regex@1.12.2
	rustix@1.1.2
	ryu@1.0.20
	scopeguard@1.2.0
	serde@1.0.228
	serde_core@1.0.228
	serde_derive@1.0.228
	serde_json@1.0.145
	serde_repr@0.1.20
	smallvec@1.15.1
	strsim@0.11.1
	syn@2.0.111
	syscalls@0.8.1
	unicode-ident@1.0.22
	unicode-segmentation@1.12.0
	unicode-width@0.2.2
	utf8parse@0.2.2
	uzers@0.12.1
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-link@0.2.1
	windows-sys@0.61.2
"

inherit cargo

DESCRIPTION="A pretty (simple) alternative to strace"
HOMEPAGE="https://github.com/JakWai01/lurk"
SRC_URI="
	https://github.com/JakWai01/lurk/archive/v${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="|| ( Apache-2.0 MIT )"
# Dependent crate licenses
LICENSE+="
	BSD-2 MIT Unicode-3.0
	|| ( Apache-2.0 Boost-1.0 )
"
SLOT="0"
KEYWORDS="~amd64"
