# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.16.0
# renovate: datasource=github-tags depName=Andrew-Velox/animfetch
# Current version: 0.1.5

EAPI=8

CRATES="
	bitflags@2.13.1
	cfg-if@1.0.4
	convert_case@0.10.0
	crossterm@0.29.0
	crossterm_winapi@0.9.1
	derive_more-impl@2.1.1
	derive_more@2.1.1
	document-features@0.2.12
	equivalent@1.0.2
	errno@0.3.14
	hashbrown@0.17.1
	indexmap@2.14.0
	libc@0.2.189
	linux-raw-sys@0.12.1
	litrs@1.0.0
	lock_api@0.4.14
	log@0.4.33
	mio@1.2.2
	parking_lot@0.12.5
	parking_lot_core@0.9.12
	proc-macro2@1.0.107
	quote@1.0.47
	redox_syscall@0.5.18
	rustc_version@0.4.1
	rustix@1.1.4
	scopeguard@1.2.0
	semver@1.0.28
	serde@1.0.229
	serde_core@1.0.229
	serde_derive@1.0.229
	serde_spanned@1.1.1
	signal-hook-mio@0.2.5
	signal-hook-registry@1.4.8
	signal-hook@0.3.18
	smallvec@1.15.2
	syn@2.0.119
	syn@3.0.3
	toml@0.9.12+spec-1.1.0
	toml_datetime@0.7.5+spec-1.1.0
	toml_parser@1.1.3+spec-1.1.0
	toml_writer@1.1.2+spec-1.1.0
	unicode-ident@1.0.24
	unicode-segmentation@1.13.3
	unicode-width@0.2.2
	wasi@0.11.1+wasi-snapshot-preview1
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-link@0.2.1
	windows-sys@0.61.2
	winnow@0.7.15
	winnow@1.0.4
"

RUST_MIN_VER="1.88.0"
inherit cargo

DESCRIPTION="Animated system fetch that stays pinned above your shell while you work"
HOMEPAGE="https://github.com/Andrew-Velox/animfetch"
SRC_URI="
	https://github.com/Andrew-Velox/animfetch/archive/v${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+=" MIT Unicode-3.0"
SLOT="0"
KEYWORDS="~amd64"
